config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  get "about", to: "about#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<p id="notice"><%= notice %></p>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="About Us Page">
    <meta name="author" content="Julian Smith">
    <title>About Us</title>
  </head>
  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Portfolios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_out" data-method="Delete" data-confirm="Are you sure?">Sign-out</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign-in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign-up</a>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Useful Links</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/projects">Projects</a>
              <a class="dropdown-item" href="https://github.com/JulesVerne22/cs3300">GitHub</a>
              <a class="dropdown-item" href="/about">About Us</a>
            </div>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <!--Main Body-->
    <main role="main">
        <!--Main Title-->
        <div class="jumbotron">
          <div class="container">
            <div class="row justify-content-md-center">
              <h1 class="display-3">About Us</h1>
              <p></p>
            </div>
          </div>
        </div>
  
        <!--Information-->
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-md-4">
              <h2>Purpose</h2>
              <p>This website was created by Julian Smith for CS3300: Software Engineering at the University of Colorado Colorado Springs.</p>
            </div>
            <div class="col-md-4">
                <h2>Technology</h2>
                <p>
                    We leveraged Ruby on Rails along with Bootstrap in order to create a cohesive website efficiently and effectively. Docker
                    and other CI/CD tools such as Heroku and CircleCI were also used. 
                </p>
            </div>
          </div>
          <br>
          <br>
          <div class="row justify-content-md-center">
            <h2>
                Future Development
            </h2>
          </div>
          <div class="row justify-content-md-center">
            <p>
                If you are interested in contributing to this project, the below links provide easy access to all the necessary resources.
            </p>
          </div>
          <div class="row justify-content-md-center">
            <a href="https://github.com/JulesVerne22/cs3300" class="link-primary">GitHub Repo</a>
          </div>
          <div class="row justify-content-md-center">
            <a href="https://app.circleci.com/pipelines/github/JulesVerne22/cs3300" class="link-primary">CircleCI Pipeline</a>
          </div>
          <div class="row justify-content-md-center">
            <a href="https://juliansmith.herokuapp.com" class="link-primary">Heroku Webpage</a>
          </div>
          <div class="row justify-content-md-center">
            <a href="https://app.julianinnovation.com" class="link-info">Personal Webpage</a>
          </div>
          <hr>
        </div>
      </main>
  
      <!--Footer-->
    <footer class="container"></footer>
    <div class="container">
      <div class="row justify-content-md-center">
        <p>&copy; Julian Inc. 2022-Present</p>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br \>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %><br \>
    <%= form.text_area :description, :cols => 30, :rows => 5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<p id="notice"><%= notice %></p>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Edit Project Page">
    <meta name="author" content="Julian Smith">
    <title>Edit <%= @project %></title>
  </head>
  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Portfolios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_out" data-method="Delete" data-confirm="Are you sure?">Sign-out</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign-in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign-up</a>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Useful Links</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/projects">Projects</a>
              <a class="dropdown-item" href="https://github.com/JulesVerne22/cs3300">GitHub</a>
              <a class="dropdown-item" href="/about">About Us</a>
            </div>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <br>
    <br>
    <br>
    <br>
    <br>
    <body class="text-center">
      <h1 class="h3 mb-3 font-weight-normal">Please edit project</h1>
      <div class="row justify-content-md-center">
          <div class="col-md-3">
              <div class="card mb-4 box-shadow">
                  <br>
                  <div class="row justify-content-md-center">
                    <div class="col-md-12">
                      <%= render 'form', project: @project %>
                    </div>
                  </div>
                  <div class="row justify-content-md-center">
                      <div class="col-md-6">
                          <%= link_to 'Show', @project %> |  
                          <%= link_to 'Back', projects_path %>
                      </div>
                  </div>
                  <br>
              </div>
          </div>
      </div>
    </body>

    <br>
    <br>
    <br>

    <!--Footer-->
    <footer class="container"></footer>
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-4">
            <p>&copy; Julian Inc. 2022-Present</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Home Page">
    <meta name="author" content="Julian Smith">
    <title>Home</title>
  </head>
  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Portfolios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_out" data-method="Delete" data-confirm="Are you sure?">Sign-out</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign-in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign-up</a>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Useful Links</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/projects">Projects</a>
              <a class="dropdown-item" href="https://github.com/JulesVerne22/cs3300">GitHub</a>
              <a class="dropdown-item" href="/about">About Us</a>
            </div>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <!--Main Body-->
    <main role="main">
      <!--Main Title-->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Portfolio</h1>
          <p></p>
        </div>
      </div>

      <!--Information-->
      <div class="container">
        <div class="row">
          <% @projects.each do |project| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-header">
                  <h2><%= project.title %></h2>
                </div>
                <div class="card-body">
                  <p class="card-text" style="font-size: 16px" id="substring-<%= project.id %>">
                    <script type="text/javascript">
                      str = "<%= project.description %>";
                      document.getElementById('substring-<%= project.id %>').innerHTML = str.substring(0,150) + "...";
                    </script>
                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-outline-secondary" href="projects/<%= project.id %>" role="button">More Details</a>
                      <% if user_signed_in? %>
                        <a class="btn btn-sm btn-outline-secondary" href="projects/<%= project.id %>/edit" role="button">Edit</a>
                        <a class="btn btn-sm btn-outline-secondary" href="projects/<%= project.id %>" data-method="delete" data-confirm="Are you sure?" role="button">Delete</a>
                      <% else %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <hr>
      </div>
      <div class="container">
        <% if user_signed_in? %>
          <div class="row">
           <div class="col-md-4">
              <p><a class="btn btn-secondary" href="projects/new" role="button">New Project</a></p>
           </div>
          </div>
        <% else %>
        <% end %>
        <br>
        <br>
      </div>
    </main>

    <!--Footer-->
    <footer class="container"></footer>
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-4">
            <p>&copy; Julian Inc. 2022-Present</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/projects/new.html.erb
<p id="notice"><%= notice %></p>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="New Project Page">
    <meta name="author" content="Julian Smith">
    <title>New Project</title>
  </head>
  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Portfolios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_out" data-method="Delete" data-confirm="Are you sure?">Sign-out</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign-in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign-up</a>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Useful Links</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/projects">Projects</a>
              <a class="dropdown-item" href="https://github.com/JulesVerne22/cs3300">GitHub</a>
              <a class="dropdown-item" href="/about">About Us</a>
            </div>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <br>
    <br>
    <br>
    <br>
    <br>
    <body class="text-center">
      <h1 class="h3 mb-3 font-weight-normal">Please create project</h1>
      <div class="row justify-content-md-center">
          <div class="col-md-3">
              <div class="card mb-4 box-shadow">
                  <br>
                  <div class="row justify-content-md-center">
                    <div class="col-md-12">
                      <%= render 'form', project: @project %>
                    </div>
                  </div>
                  <div class="row justify-content-md-center">
                      <div class="col-md-6">
                          <%= link_to 'Back', projects_path %>
                      </div>
                  </div>
                  <br>
              </div>
          </div>
      </div>
    </body>

    <br>
    <br>
    <br>

    <!--Footer-->
    <footer class="container"></footer>
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-4">
            <p>&copy; Julian Inc. 2022-Present</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>


<!-- <h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %> -->

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>